### PR TITLE
Information reload

### PR DESCRIPTION
**Pull request by t-laird**

### CODE REVIEW

**Comment by katiescruggs** [comment]
Seems like a good move to move Login into Routes since it's not adding that many lines of code! Question: why are there mockProps in your Routes component?

**Comment by t-laird** [comment]
Thank you! I added component will receive props as a way of determining when user information should be appropriately updated. I need the component to do that initially, as well. Since componentWillReceiveProps doesn’t fire on mount I’m calling it synthetically from componentDidMount and mocking what nextProps should be.

**Comment by HartiganHM** [comment]
Looks like a smart refactor and consolidates a lot of duplicate code that you had going on! In your `componentWillReceiveProps` you use `this.props.location.pathname` eight times. I would consider setting that to a variable inside of the lifecycle method. Should cut down on redundant code and make it a little more readable!

**Comment by t-laird** [comment]
great idea! I went ahead and did that, thanks for the input!

**Pull request merged**
